apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: memcached-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
  description: memcached sample operator
  displayName: Memcached
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cache
  - memcache
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maturity: alpha
  provider:
    name: atef
  version: 0.0.0
